version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/trading_bot
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  dashboard:
    build: .
    command: python -m stockapp.dashboard
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/trading_bot
    depends_on:
      - app
    ports:
      - "8050:8050"
    volumes:
      - .:/app

volumes:
  db_data: 